### ISSUE TITLE
Creación de un curso

### ISSUE THREAD

**Issue by QuinsZouls** [QuinsZouls/proyecto-final-movil#13]
Deberán escoger una tématica relacionada con finanzas para la elaboración del curso, el curso deberá contar con los siguientes elementos:

- Mínimo 3 secciones con información (puede ser texto, una imágen o un video de youtube)
- Mínimo 5 preguntas de opción múltiple con sus respectivas respuestas
- Deberá ser adecuado para cualquier público

**Comment by anahi1234567890** [comment]
[https://docs.google.com/document/d/1lU44Sux2yZTRpMazbhM6GmsxTjTcf4q4djdw7-vDnEA/edit?usp=sharing](url)
